### PR TITLE
Correct the license copies

### PR DESCRIPTION
**Pull request by nedbat**
We said Apache, and it is Apache, so why have a copy of AGPL?

### CODE REVIEW

**Comment by nedbat** [comment]
@giovannicimolin A simple fix.

**Comment by giovannicimolin** [comment]
:+1: 

I've checked the original discussion at #1 (where the LICENSE file was introduced) and also https://open.edx.org/trademark-licensing-details/.

LGTM.

**Comment by nedbat** [comment]
OK, I've switched to AGPL.

**Review by giovannicimolin — APPROVED** [review]
:+1:

- [x] I read through the changes
- [x] Includes documentation

**Pull request merged**
