### PR TITLE
Update translations (autogenerated message)

### PR DESCRIPTION
**Pull request by OmarIthawi**
As described.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-3763](https://openedx.atlassian.net/browse/OSPR-3763) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution.

**Comment by natabene** [comment]
@douglashall Is this something you can help review?

**Comment by natabene** [comment]
@douglashall Thanks! Do you want someone else from edX have a look or can you merge now?

**Comment by douglashall** [comment]
@natabene I can merge if you need me to. Maybe we should give you the ability to merge PRs?

**Comment by edx-webhook** [comment]
@OmarIthawi 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-lti-consumer&entry.867055334=https://github.com/edx/xblock-lti-consumer/pull/47&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2019-07-27+10:54&entry.1917517419=2019-07-29+14:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
