### PR TITLE
Add Portuguese (Portugal) translation

### PR DESCRIPTION
**Pull request by MoisesGSalas**
Add Portuguese of Portugal translations.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @MoisesGSalas! I've created [OSPR-5934](https://openedx.atlassian.net/browse/OSPR-5934) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@Thank you for the contribution! Once you have signed our Contributor Agreement and it has been processed, you will receive a confirmation via email from our Legal team. We then will be able to review this and all your future code contributions.

Please note that our translations are added via [Transifex](https://www.transifex.com/open-edx/edx-platform/).

**Comment by MoisesGSalas** [comment]
@natabene The issue with the contributor agreement should be sorted out by now.

About transifex, what I did was simply add a new locale (pt-PT) and pull the translations that were already in transifex so it should be fine.

**Comment by giovannicimolin** [comment]
@nedbat @natabene I can review this as core committer early next week.

**Comment by natabene** [comment]
@giovannicimolin Excellent, thanks for offering.

**Comment by natabene** [comment]
@MoisesGSalas You are all set with us regarding the agreement.

**Review by giovannicimolin — APPROVED** [review]
:+1:

- [x] I tested this:
1. Installed this branch of the LTI consumer in the devstack.
2. Set the LMS `LANGUAGE_CODE` to `pt-pt`.
3. Checked that the translated strings were displayed properly (like [this one](https://www.transifex.com/open-edx/xblocks/viewstrings/#pt_PT/lti-consumer/86829378) - not present in the `pt-BR` translation).
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ NA: just pulling translation files.
- [ ] ~~Includes documentation~~ NA

@MoisesGSalas Thanks for the contribution!

Can you do the following before I merge?
- Reword your commit to use [OEP-51: Conventional commits](https://open-edx-proposals.readthedocs.io/en/latest/oep-0051-bp-conventional-commits.html). E.g. make the commit message like this: `feat: Add Portuguese (Portugal) translation`
- Do a minor version bump on the block (change [this line](https://github.com/edx/xblock-lti-consumer/blob/master/setup.py#L52) to `3.0.2`)

@nedbat @davidjoy (CC @sarina) This is my first OSPR CC review, how can we coordinate the merge for small changes like these? Should I merge directly once the comments are addressed?

**Comment by sarina** [comment]
@giovannicimolin definitely go ahead and merge once you see fit!

**Comment by MoisesGSalas** [comment]
@giovannicimolin thank you for the review. I made the changes you requested, you can tell me if there's anything else you need.

**Comment by giovannicimolin** [comment]
@MoisesGSalas Perfect, thank you! 
@sarina I'll merge this since these are trivial changes and draft a release, but I'm not sure how the release process (for PyPi) works.

**Comment by giovannicimolin** [comment]
@sarina The CI on master failed mentioning that the package upload failed, but the new version is there (https://pypi.org/project/lti-consumer-xblock/3.0.2/).

**Comment by sarina** [comment]
Huh! I think(?) @nedbat mentioned that being a thing that happens. @stvstnfrd may know more. But if it works it works 🤷‍♀️

**Comment by stvstnfrd** [comment]
> @stvstnfrd may know more

I actually don't know about this one :shrug:

**Pull request merged**
