### PR TITLE
feat: replace jsonfield2 with jsonfield 

### PR DESCRIPTION
**Pull request by iamsobanjaved**
Replacing `jsonfield2` with `jsonfield` as the former is merged back into the latter one.

BOM-2447

### CODE REVIEW

**Comment by iamsobanjaved** [comment]
Created this PR again as previous PR (https://github.com/edx/xblock-lti-consumer/pull/146) was reverted here (https://github.com/edx/xblock-lti-consumer/pull/155)

**Comment by jmbowman** [comment]
@sarina This is one of the blockers for the Django 3.2 upgrade, could someone on CE (repo owner) please review this?  It's a change that was already merged once, but had to be reverted because it has to be deployed concurrently with similar updates in a few other edx-platform dependencies.

**Comment by sarina** [comment]
@nedbat , @Agrendalath , @giovannicimolin , or @xitij2000 - could one of you review this Django 3.2 upgrade PR?

**Comment by xitij2000** [comment]
> @nedbat , @Agrendalath , @giovannicimolin , or @xitij2000 - could one of you review this Django 3.2 upgrade PR?

On it.

**Comment by xitij2000** [comment]
> Replacing `jsonfield2` with `jsonfield` as the former is merged back into the latter one.

Django 3.1 and above now includes an in-built JSONField, is there a reason to still use a third-party dependency for this?

**Comment by jmbowman** [comment]
I suspect we will want to switch to Django's JSONField, but need to wait until after we drop support for Django 2.2 to do so.  So that'll come after the Django 3.2 upgrade is finished.  (I mentioned this briefly in [Django 3.2 Upgrade: Key Changes](https://openedx.atlassian.net/wiki/spaces/AC/pages/3066626061/Django+3.2+Upgrade+Key+Changes).)

**Review by xitij2000 — APPROVED** [review]
:+1:

I've tested this code on the master devstack, and don't see any issues. This looks good to merge to me. 

- [x] I tested this: tested on master devstack with both LTI 1.1 and 1.3 setup
- [x] I read through the code
- [na] I checked for accessibility issues
- [na] Includes documentation

**Pull request merged**
