### PR TITLE
Update translations (autogenerated message)

### PR DESCRIPTION
**Pull request by OmarIthawi**
We've just got `fr_CA` translated to :100: :tada: . I'm updating the upstream repo.

The `.mo` files were stale due to the lack of a script to translate them, therefore the change in all of them.

 - [x] Get the `fr_CA` :100: translated
 - [x] Pull from Transifex
 - [x] Test on devstack
 - [ ] Get it reviewed
 - [ ] Bump up the version?
 - [ ] Merge the PR

cc: @natabene

### CODE REVIEW

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by OmarIthawi** [comment]
Thanks @natabene for passing here. I've tested it on devstack it works well.

image

image

As you can see `External Resource` is not translated. That's a bug in the code because it's hardcoded:

https://github.com/edx/xblock-lti-consumer/blob/5c4699cf052b5055a557d40ad15ee8c33f99e4c3/lti_consumer/templates/html/student.html#L3

It's a bug for another day that is out of the scope of this pull request. So this one is ready to get merged.

**Comment by natabene** [comment]
@scottrish Can you give this a look as soon as you can?

**Comment by edx-webhook** [comment]
@OmarIthawi 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-lti-consumer&entry.867055334=https://github.com/edx/xblock-lti-consumer/pull/48&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2019-08-28+16:50&entry.1917517419=2019-09-10+17:40&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by OmarIthawi** [comment]
Thanks @nedbat and @natabene for the help!

**Pull request merged**
