### PR TITLE
[BD-24][TNL-7824][BB-3373]: Implement ltiResourceLink deep linking content presentation

### PR DESCRIPTION
**Pull request by giovannicimolin**
This PR implements the base LTI Deep Linking content presentation for `ltiResourceLink` types.
68d9c510cba3b78490c48ce8fc83c9a4b0ba5481: contains the full code changes.
5973a4350416ff61bef4e2321685cfe38986b10f: adds tests to check functionality.

**Testing instructions:**
1. Checkout this branch.
2. Set up a local LTI tool (recommended: https://github.com/dmitry-viskov/pylti1.3-django-example) and ngrok tunnel.
3. Do a deep link launch (from Studio link).
5. Select an option in the LTI tool's UI.
6. Go to http://localhost:18000/admin/lti_consumer/ltidlcontentitem/ and check that the option you selected is stored in the model.
7. Go to the LMS and load the LTI section.
8. Check that the local tool opens with the configuration you've selected in step 5.

**Conformance testing:**
1. Set up LTI + Deep linking.
2. Do a LTI launch using the Studio links and post it back to the LMS.
3. Open the LTI section in the LMS, the content from the IMS tool should load.
4. Take a screenshot and upload to their conformance tool.

**Reviewers:**
- [x] @shimulch 
- [ ] @nedbat

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @giovannicimolin! I've created [BLENDED-748](https://openedx.atlassian.net/browse/BLENDED-748) to keep track of it in Jira.   More details are on the [BD-24](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545076784/BD-24+LTI+v1.3+Improvements+Advantage+Support) project page.


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by shimulch — APPROVED** [review]
LGTM :+1: 

- [x] I tested this in my local devstack. I have done a deep linking launch from studio and ensure that DL launch from LMS respects the option selected via studio DL lauch.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation
- [N/A] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

**Comment by giovannicimolin** [comment]
@nedbat This is ready for review.

**Comment by nedbat** [comment]
Does this PR need any of the currently unmerged PRs in order to test it?

**Comment by giovannicimolin** [comment]
@nedbat No, it's complete on it's own :)

**Review by nedbat — APPROVED** [review]

**Pull request merged**
