### PR TITLE
[BD-2] Validate preflight response

### PR DESCRIPTION
**Pull request by viadanna**
This PR adds validation to the preflight response used by the LTI 1.3 launch flow.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @viadanna! I've created [OSPR-4440](https://openedx.atlassian.net/browse/OSPR-4440) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@viadanna Thank you for your contribution. Is this PR part of the Blended project?

**Comment by giovannicimolin** [comment]
@natabene Yes, this is related to the BD-2 project!
@viadanna Can you edit the title and add `[BD-2]` prefix?

**Comment by giovannicimolin** [comment]
@viadanna Can you rebase this PR?

**Comment by giovannicimolin** [comment]
@davidjoy @davestgermain This is ready for review.

**Comment by giovannicimolin** [comment]
@davidjoy Can you merge this PR? We don't have permissions for doing so.

**Comment by edx-webhook** [comment]
@viadanna 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/xblock-lti-consumer&entry.867055334=https://github.com/edx/xblock-lti-consumer/pull/60&entry.1484655318=https://github.com/viadanna&entry.752974735=2020-04-30+19:00&entry.1917517419=2020-06-02+21:12&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
